version: "3"
services:
  mongo:
    restart: always
    image: mongo
    container_name: mongodb_lulas
    ports:
    - "27017:27017"
    volumes:
       - ./data/db:/data/db
    networks:
       - reseau_bd
    command: mongod --port 27017 --quiet --logpath /dev/null
  

  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      #- ME_CONFIG_MONGODB_ADMINUSERNAME=root
      #- ME_CONFIG_MONGODB_ADMINPASSWORD=password
      #- ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb_lulas:27017
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    
    networks:
      - reseau_bd
    restart: always
    ports:
      - "8081:8081"


  lulas:
    #restart: always
    image: lulas:1.0
    container_name: lulas
    depends_on:
    - "mongo"
    networks:
    - reseau_bd
    environment:
    - MONGO_ADDRESS=mongodb_lulas
    - DB=lulas
    - COLLECTION=nameservers_ipv4_status
    - PORT=27017
    volumes:
       - ./:/home
    #apt-get update && apt-get install python3 pip iputils-ping -y && pip install -r /home/requirements.txt &&
    command: sh -c "python3 /home/worker/main.py"

  map:
    #restart: always
    image: uvicornmap:1.0.0
    container_name: map
    depends_on:
    - "mongo"
    networks:
    - reseau_bd
    ports:
    - "8080:8080"
    environment:
    - MONGO_ADDRESS=mongodb_lulas
    - DB=lulas
    - COLLECTION=nameservers_ipv4_status
    - PORT=27017
    volumes:
       - ./:/home
    #apt-get update && apt-get install python3 pip iputils-ping -y && pip install -r /home/requirements.txt &&
    command: sh -c "cd /home/map && python3 main.py"
networks:
  reseau_bd:
    driver: bridge
